### ISSUE TITLE
The GPWS does not work.

### ISSUE THREAD

**Issue by iL0g1c** [Ariakim-Taiyo/777-Realism-Overhaul#3]
The links to the callouts give a 404 error. I replaced the links with my own hosted gpws callouts, but it still appeared not to work. There may be an under lying issue.

**Comment by Ariakim-Taiyo** [comment]
The web server i am hosting those sounds on has had some issues recently, and i have to manually reupload the files for all of the sounds. There is a specific format that the audio files and the server setup follows to ensure everything works together. The issue should be fixed shortly, as i am in the process of reuploading the affected files. Most of the files are back up for the liverychanger and A321Neo as well as my aircraft sounds for my cc planes.

**Comment by iL0g1c** [comment]
So, why is it when I try to host the files myself it still doesn't work?

**Comment by Ariakim-Taiyo** [comment]
It is likely a CORS error. Either that r it is using an unsupported file format. As far as i can see, you cannot host files on github and then use them elsewhere due to CORS policies. You either have to find a true host or set up a web server yourself.

**Comment by Ariakim-Taiyo** [comment]
Sounds are now fixed @iL0g1c
